### PR TITLE
Some fixes and improvements

### PR DESCRIPTION
**Pull request by ao2**
Hi,

here are some fixes and improvements for siriusphp/upload.

The details of the changes are in the commit messages.

If you end up applying these changes, could you please also tag a new stable release and update the version on packagist?

Thanks,
   Antonio

### CODE REVIEW

**Comment by ao2** [comment]
ping

**Comment by adrianmiu** [comment]
@ao2  Thank you!

**Comment by ao2** [comment]
@adrianmiu awesome, any ETA for a new stable release on packagist?

**Comment by adrianmiu** [comment]
@ao2 I've just added the new version 2.1.1

**Comment by ao2** [comment]
Cool, thanks.

**Pull request merged**
